In [54]:
# ==========================================================
# Day 3: Data Cleaning & Preprocessing
# Project: RetailIQ Analytics Platform
# ==========================================================

# Import Libraries
import pandas as pd
import numpy as np
import os

# Display Settings
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", 120)
pd.set_option("display.max_colwidth", None)

print("=" * 60)
print("RetailIQ Analytics Platform")
print("Day 3 - Data Cleaning & Preprocessing")
print("Libraries Imported Successfully")
print("=" * 60)

============================================================
RetailIQ Analytics Platform
Day 3 - Data Cleaning & Preprocessing
Libraries Imported Successfully
============================================================

In [77]:
# ==========================================================
# Load Raw Datasets
# ==========================================================

customers = pd.read_csv("../data/raw/olist_customers_dataset.csv")
orders = pd.read_csv("../data/raw/olist_orders_dataset.csv")
order_items = pd.read_csv("../data/raw/olist_order_items_dataset.csv")
payments = pd.read_csv("../data/raw/olist_order_payments_dataset.csv")
reviews = pd.read_csv("../data/raw/olist_order_reviews_dataset.csv")
products = pd.read_csv("../data/raw/olist_products_dataset.csv")
sellers = pd.read_csv("../data/raw/olist_sellers_dataset.csv")
geolocation = pd.read_csv("../data/raw/olist_geolocation_dataset.csv")
category_translation = pd.read_csv("../data/raw/product_category_name_translation.csv")

print("All datasets loaded successfully!\n")

datasets = {
    "Customers": customers,
    "Orders": orders,
    "Order Items": order_items,
    "Payments": payments,
    "Reviews": reviews,
    "Products": products,
    "Sellers": sellers,
    "Geolocation": geolocation,
    "Category Translation": category_translation
}

for name, df in datasets.items():
    print(f"{name:<22} Shape: {df.shape}")

All datasets loaded successfully!

Customers              Shape: (99441, 5)
Orders                 Shape: (99441, 8)
Order Items            Shape: (112650, 7)
Payments               Shape: (103886, 5)
Reviews                Shape: (99224, 7)
Products               Shape: (32951, 9)
Sellers                Shape: (3095, 4)
Geolocation            Shape: (1000163, 5)
Category Translation   Shape: (71, 2)

In [95]:
#
datasets = {
    "customers": customers,
    "geolocation": geolocation,
    "orders": orders,
    "order_items": order_items,
    "payments": payments,
    "reviews": reviews,
    "products": products,
    "sellers": sellers,
    "category_translation": category_translation
}

In [112]:
# ==========================================================
# Create Working Copies
# ==========================================================

customers_clean = customers.copy()
orders_clean = orders.copy()
order_items_clean = order_items.copy()
payments_clean = payments.copy()
reviews_clean = reviews.copy()
products_clean = products.copy()
sellers_clean = sellers.copy()
geolocation_clean = geolocation.copy()

print("Working copies created successfully!")

Working copies created successfully!

In [128]:
# ==========================================================
# Step 4: Dataset Inspection
# ==========================================================

def inspect_dataset(df, name):
    print("=" * 80)
    print(f"Dataset: {name}")
    print("=" * 80)

    # Shape
    print(f"\nShape: {df.shape}")

    # Data Types
    print("\nData Types:")
    print(df.dtypes)

    # Missing Values
    print("\nMissing Values:")
    missing = df.isnull().sum()
    missing = missing[missing > 0]

    if len(missing) == 0:
        print("No missing values.")
    else:
        print(missing.sort_values(ascending=False))

    # Duplicate Rows
    print(f"\nDuplicate Rows: {df.duplicated().sum()}")

    # Memory Usage
    memory = df.memory_usage(deep=True).sum() / 1024**2
    print(f"\nMemory Usage: {memory:.2f} MB")

    print("\nFirst 5 Rows:")
    display(df.head())

    print("\n")

In [143]:
datasets = {
    "Customers": customers_clean,
    "Orders": orders_clean,
    "Order Items": order_items_clean,
    "Payments": payments_clean,
    "Reviews": reviews_clean,
    "Products": products_clean,
    "Sellers": sellers_clean,
    "Geolocation": geolocation_clean
}

for name, df in datasets.items():
    inspect_dataset(df, name)

================================================================================
Dataset: Customers
================================================================================

Shape: (99441, 5)

Data Types:
customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object

Missing Values:
No missing values.

Duplicate Rows: 0

Memory Usage: 29.62 MB

First 5 Rows:

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

================================================================================
Dataset: Orders
================================================================================

Shape: (99441, 10)

Data Types:
order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                        object
order_delivered_carrier_date             object
order_delivered_customer_date            object
order_estimated_delivery_date            object
purchase_year                             int32
purchase_month                           object
dtype: object

Missing Values:
order_delivered_customer_date    2965
order_delivered_carrier_date     1783
order_approved_at                 160
dtype: int64

Duplicate Rows: 0

Memory Usage: 58.85 MB

First 5 Rows:

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,purchase_year,purchase_month
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,2017,October
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,2018,July
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,2018,August
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,2017,November
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,2018,February

================================================================================
Dataset: Order Items
================================================================================

Shape: (112650, 7)

Data Types:
order_id                object
order_item_id            int64
product_id              object
seller_id               object
shipping_limit_date     object
price                  float64
freight_value          float64
dtype: object

Missing Values:
No missing values.

Duplicate Rows: 0

Memory Usage: 39.43 MB

First 5 Rows:

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

================================================================================
Dataset: Payments
================================================================================

Shape: (103886, 5)

Data Types:
order_id                 object
payment_sequential        int64
payment_type             object
payment_installments      int64
payment_value           float64
dtype: object

Missing Values:
No missing values.

Duplicate Rows: 0

Memory Usage: 17.81 MB

First 5 Rows:

                           order_id  payment_sequential payment_type  payment_installments  payment_value
0  b81ef226f3fe1789b1e8b2acac839d17                   1  credit_card                     8          99.33
1  a9810da82917af2d9aefd1278f1dcfa0                   1  credit_card                     1          24.39
2  25e8ea4e93396b6fa0d3dd708e76c1bd                   1  credit_card                     1          65.71
3  ba78997921bbcdc1373bb41e913ab953                   1  credit_card                     8         107.78
4  42fdf880ba16b47b59251dd489d4441a                   1  credit_card                     2         128.45

================================================================================
Dataset: Reviews
================================================================================

Shape: (99224, 7)

Data Types:
review_id                  object
order_id                   object
review_score                int64
review_comment_title       object
review_comment_message     object
review_creation_date       object
review_answer_timestamp    object
dtype: object

Missing Values:
review_comment_title      87656
review_comment_message    58247
dtype: int64

Duplicate Rows: 0

Memory Usage: 42.75 MB

First 5 Rows:

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela Internet seguro e prático Parabéns a todos feliz Páscoa,2018-03-01 00:00:00,2018-03-02 10:26:53

================================================================================
Dataset: Products
================================================================================

Shape: (32951, 9)

Data Types:
product_id                     object
product_category_name          object
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

Missing Values:
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

Duplicate Rows: 0

Memory Usage: 6.79 MB

First 5 Rows:

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

================================================================================
Dataset: Sellers
================================================================================

Shape: (3095, 4)

Data Types:
seller_id                 object
seller_zip_code_prefix     int64
seller_city               object
seller_state              object
dtype: object

Missing Values:
No missing values.

Duplicate Rows: 0

Memory Usage: 0.66 MB

First 5 Rows:

                          seller_id  seller_zip_code_prefix        seller_city seller_state
0  3442f8959a84dea7ee197c632cb2df15                   13023           campinas           SP
1  d1b65fc7debc3361ea86b5f14c68d2e2                   13844         mogi guacu           SP
2  ce3ad9de960102d0677a81f5d0bb7b2d                   20031     rio de janeiro           RJ
3  c0f3eea2e14555b6faeea3dd58c1b1c3                    4195          sao paulo           SP
4  51a04a8a6bdcb23deccc82b0b80742cf                   12914  braganca paulista           SP

================================================================================
Dataset: Geolocation
================================================================================

Shape: (1000163, 5)

Data Types:
geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                object
geolocation_state               object
dtype: object

Missing Values:
No missing values.

Duplicate Rows: 261831

Memory Usage: 146.09 MB

First 5 Rows:

   geolocation_zip_code_prefix  geolocation_lat  geolocation_lng geolocation_city geolocation_state
0                         1037       -23.545621       -46.639292        sao paulo                SP
1                         1046       -23.546081       -46.644820        sao paulo                SP
2                         1046       -23.546129       -46.642951        sao paulo                SP
3                         1041       -23.544392       -46.639499        sao paulo                SP
4                         1035       -23.541578       -46.641607        sao paulo                SP

In [157]:
# ==========================================================
# Customers Cleaning
# ==========================================================

print("Customers Shape Before:", customers_clean.shape)

# Remove duplicate rows
customers_clean.drop_duplicates(inplace=True)

# Check missing values
print("\nMissing Values:")
print(customers_clean.isnull().sum())

print("\nCustomers Shape After:", customers_clean.shape)

Customers Shape Before: (99441, 5)

Missing Values:
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

Customers Shape After: (99441, 5)

In [170]:
# ==========================================================
# Orders Cleaning
# ==========================================================

print("Orders Shape Before:", orders_clean.shape)

# Remove duplicate rows
orders_clean.drop_duplicates(inplace=True)

# Convert date columns to datetime
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in date_columns:
    orders_clean[col] = pd.to_datetime(orders_clean[col])

print("\nMissing Values:")
print(orders_clean.isnull().sum())

print("\nOrders Shape After:", orders_clean.shape)

Orders Shape Before: (99441, 10)

Missing Values:
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
purchase_year                       0
purchase_month                      0
dtype: int64

Orders Shape After: (99441, 10)

In [182]:
print("Order Items Shape Before:", order_items_clean.shape)

order_items_clean.drop_duplicates(inplace=True)

print("\nMissing Values:")
print(order_items_clean.isnull().sum())

print("\nOrder Items Shape After:", order_items_clean.shape)

Order Items Shape Before: (112650, 7)

Missing Values:
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

Order Items Shape After: (112650, 7)

In [193]:
print("Payments Shape Before:", payments_clean.shape)

payments_clean.drop_duplicates(inplace=True)

print("\nMissing Values:")
print(payments_clean.isnull().sum())

print("\nPayments Shape After:", payments_clean.shape)

Payments Shape Before: (103886, 5)

Missing Values:
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

Payments Shape After: (103886, 5)

In [203]:
print("Reviews Shape Before:", reviews_clean.shape)

reviews_clean.drop_duplicates(inplace=True)

# Convert dates
reviews_clean["review_creation_date"] = pd.to_datetime(
    reviews_clean["review_creation_date"]
)

reviews_clean["review_answer_timestamp"] = pd.to_datetime(
    reviews_clean["review_answer_timestamp"]
)

print("\nMissing Values:")
print(reviews_clean.isnull().sum())

print("\nReviews Shape After:", reviews_clean.shape)

Reviews Shape Before: (99224, 7)

Missing Values:
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

Reviews Shape After: (99224, 7)

In [212]:
print("Products Shape Before:", products_clean.shape)

products_clean.drop_duplicates(inplace=True)

print("\nMissing Values:")
print(products_clean.isnull().sum())

print("\nProducts Shape After:", products_clean.shape)

Products Shape Before: (32951, 9)

Missing Values:
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

Products Shape After: (32951, 9)

In [220]:
print("Sellers Shape Before:", sellers_clean.shape)

sellers_clean.drop_duplicates(inplace=True)

print("\nMissing Values:")
print(sellers_clean.isnull().sum())

print("\nSellers Shape After:", sellers_clean.shape)

Sellers Shape Before: (3095, 4)

Missing Values:
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

Sellers Shape After: (3095, 4)

In [227]:
print("Geolocation Shape Before:", geolocation_clean.shape)

geolocation_clean.drop_duplicates(inplace=True)

print("\nMissing Values:")
print(geolocation_clean.isnull().sum())

print("\nGeolocation Shape After:", geolocation_clean.shape)

Geolocation Shape Before: (1000163, 5)

Missing Values:
geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

Geolocation Shape After: (738332, 5)

In [233]:
# ==========================================================
# Feature Engineering
# ==========================================================

orders_clean["purchase_year"] = (
    orders_clean["order_purchase_timestamp"].dt.year
)

orders_clean["purchase_month"] = (
    orders_clean["order_purchase_timestamp"].dt.month
)

orders_clean["purchase_day"] = (
    orders_clean["order_purchase_timestamp"].dt.day
)

orders_clean["purchase_weekday"] = (
    orders_clean["order_purchase_timestamp"].dt.day_name()
)

orders_clean["delivery_days"] = (
    orders_clean["order_delivered_customer_date"]
    - orders_clean["order_purchase_timestamp"]
).dt.days

In [238]:
print("=" * 80)
print("Final Dataset Summary")
print("=" * 80)

for name, df in datasets.items():
    print(f"{name:<20} {df.shape}")

================================================================================
Final Dataset Summary
================================================================================
Customers            (99441, 5)
Orders               (99441, 10)
Order Items          (112650, 7)
Payments             (103886, 5)
Reviews              (99224, 7)
Products             (32951, 9)
Sellers              (3095, 4)
Geolocation          (738332, 5)

In [242]:
# ==========================================================
# Save Processed Files
# ==========================================================

os.makedirs("../data/processed", exist_ok=True)

customers_clean.to_csv("../data/processed/customers_clean.csv", index=False)
orders_clean.to_csv("../data/processed/orders_clean.csv", index=False)
order_items_clean.to_csv("../data/processed/order_items_clean.csv", index=False)
payments_clean.to_csv("../data/processed/payments_clean.csv", index=False)
reviews_clean.to_csv("../data/processed/reviews_clean.csv", index=False)
products_clean.to_csv("../data/processed/products_clean.csv", index=False)
sellers_clean.to_csv("../data/processed/sellers_clean.csv", index=False)
geolocation_clean.to_csv("../data/processed/geolocation_clean.csv", index=False)

print("All cleaned datasets saved successfully!")

All cleaned datasets saved successfully!

In [245]:
print("Processed Files:\n")

for file in sorted(os.listdir("../data/processed")):
    print(file)

Processed Files:

customers_clean.csv
geolocation_clean.csv
order_items_clean.csv
orders_clean.csv
payments_clean.csv
products_clean.csv
reviews_clean.csv
sellers_clean.csv

In [246]:
import os

print(os.listdir("../data/raw"))

['olist_sellers_dataset.csv', 'product_category_name_translation.csv', 'olist_orders_dataset.csv', 'olist_order_items_dataset.csv', 'olist_customers_dataset.csv', 'olist_geolocation_dataset.csv', 'olist_order_payments_dataset.csv', 'olist_order_reviews_dataset.csv', 'olist_products_dataset.csv']