In [3]:
import pandas as pd

master = pd.read_csv("/Users/rohithjavvadi/realsalesanalytics/data/processed/master_sales_dataset.csv")

master.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,purchase_year,purchase_month,...,seller_city,seller_state,payment_value,payment_installments,payment_type,payment_count,review_score,review_count,review_comment_title,review_comment_message
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,2017,10,...,maua,SP,38.71,1.0,"credit_card, voucher",3.0,4.0,1.0,NaN,"Não testei o produto ainda, mas ele veio corre..."
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,2018,7,...,belo horizonte,SP,141.46,1.0,boleto,1.0,4.0,1.0,Muito boa a loja,Muito bom o produto.
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,2018,8,...,guariba,SP,179.12,3.0,credit_card,1.0,5.0,1.0,NaN,NaN
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,2017,11,...,belo horizonte,MG,72.20,1.0,credit_card,1.0,5.0,1.0,NaN,O produto foi exatamente o que eu esperava e e...
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,2018,2,...,mogi das cruzes,SP,28.62,1.0,credit_card,1.0,5.0,1.0,NaN,NaN

In [4]:
import sqlite3

conn = sqlite3.connect("retailiq.db")

master.to_sql(
    "orders",
    conn,
    if_exists="replace",
    index=False
)

print("Table loaded successfully!")

Table loaded successfully!

In [5]:
pd.read_sql(
    """
    SELECT *
    FROM orders
    LIMIT 5
    """,
    conn
)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,purchase_year,purchase_month,...,seller_city,seller_state,payment_value,payment_installments,payment_type,payment_count,review_score,review_count,review_comment_title,review_comment_message
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,2017,10,...,maua,SP,38.71,1.0,"credit_card, voucher",3.0,4.0,1.0,None,"Não testei o produto ainda, mas ele veio corre..."
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,2018,7,...,belo horizonte,SP,141.46,1.0,boleto,1.0,4.0,1.0,Muito boa a loja,Muito bom o produto.
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,2018,8,...,guariba,SP,179.12,3.0,credit_card,1.0,5.0,1.0,None,None
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,2017,11,...,belo horizonte,MG,72.20,1.0,credit_card,1.0,5.0,1.0,None,O produto foi exatamente o que eu esperava e e...
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,2018,2,...,mogi das cruzes,SP,28.62,1.0,credit_card,1.0,5.0,1.0,None,None

In [6]:
pd.read_sql(
    """
    PRAGMA table_info(orders);
    """,
    conn
)

    cid                           name     type  notnull dflt_value  pk
0     0                       order_id     TEXT        0       None   0
1     1                    customer_id     TEXT        0       None   0
2     2                   order_status     TEXT        0       None   0
3     3       order_purchase_timestamp     TEXT        0       None   0
4     4              order_approved_at     TEXT        0       None   0
5     5   order_delivered_carrier_date     TEXT        0       None   0
6     6  order_delivered_customer_date     TEXT        0       None   0
7     7  order_estimated_delivery_date     TEXT        0       None   0
8     8                  purchase_year  INTEGER        0       None   0
9     9                 purchase_month  INTEGER        0       None   0
10   10                   purchase_day  INTEGER        0       None   0
11   11               purchase_weekday     TEXT        0       None   0
12   12                  delivery_days     REAL        0       None   0
13   13             customer_unique_id     TEXT        0       None   0
14   14       customer_zip_code_prefix  INTEGER        0       None   0
15   15                  customer_city     TEXT        0       None   0
16   16                 customer_state     TEXT        0       None   0
17   17                  order_item_id     REAL        0       None   0
18   18                     product_id     TEXT        0       None   0
19   19                      seller_id     TEXT        0       None   0
20   20            shipping_limit_date     TEXT        0       None   0
21   21                          price     REAL        0       None   0
22   22                  freight_value     REAL        0       None   0
23   23          product_category_name     TEXT        0       None   0
24   24            product_name_lenght     REAL        0       None   0
25   25     product_description_lenght     REAL        0       None   0
26   26             product_photos_qty     REAL        0       None   0
27   27               product_weight_g     REAL        0       None   0
28   28              product_length_cm     REAL        0       None   0
29   29              product_height_cm     REAL        0       None   0
30   30               product_width_cm     REAL        0       None   0
31   31  product_category_name_english     TEXT        0       None   0
32   32         seller_zip_code_prefix     REAL        0       None   0
33   33                    seller_city     TEXT        0       None   0
34   34                   seller_state     TEXT        0       None   0
35   35                  payment_value     REAL        0       None   0
36   36           payment_installments     REAL        0       None   0
37   37                   payment_type     TEXT        0       None   0
38   38                  payment_count     REAL        0       None   0
39   39                   review_score     REAL        0       None   0
40   40                   review_count     REAL        0       None   0
41   41           review_comment_title     TEXT        0       None   0
42   42         review_comment_message     TEXT        0       None   0

In [7]:
pd.read_sql("""
SELECT COUNT(*) AS total_rows
FROM orders;
""", conn)

   total_rows
0      113425

In [8]:
pd.read_sql("""
PRAGMA table_info(orders);
""", conn)

    cid                           name     type  notnull dflt_value  pk
0     0                       order_id     TEXT        0       None   0
1     1                    customer_id     TEXT        0       None   0
2     2                   order_status     TEXT        0       None   0
3     3       order_purchase_timestamp     TEXT        0       None   0
4     4              order_approved_at     TEXT        0       None   0
5     5   order_delivered_carrier_date     TEXT        0       None   0
6     6  order_delivered_customer_date     TEXT        0       None   0
7     7  order_estimated_delivery_date     TEXT        0       None   0
8     8                  purchase_year  INTEGER        0       None   0
9     9                 purchase_month  INTEGER        0       None   0
10   10                   purchase_day  INTEGER        0       None   0
11   11               purchase_weekday     TEXT        0       None   0
12   12                  delivery_days     REAL        0       None   0
13   13             customer_unique_id     TEXT        0       None   0
14   14       customer_zip_code_prefix  INTEGER        0       None   0
15   15                  customer_city     TEXT        0       None   0
16   16                 customer_state     TEXT        0       None   0
17   17                  order_item_id     REAL        0       None   0
18   18                     product_id     TEXT        0       None   0
19   19                      seller_id     TEXT        0       None   0
20   20            shipping_limit_date     TEXT        0       None   0
21   21                          price     REAL        0       None   0
22   22                  freight_value     REAL        0       None   0
23   23          product_category_name     TEXT        0       None   0
24   24            product_name_lenght     REAL        0       None   0
25   25     product_description_lenght     REAL        0       None   0
26   26             product_photos_qty     REAL        0       None   0
27   27               product_weight_g     REAL        0       None   0
28   28              product_length_cm     REAL        0       None   0
29   29              product_height_cm     REAL        0       None   0
30   30               product_width_cm     REAL        0       None   0
31   31  product_category_name_english     TEXT        0       None   0
32   32         seller_zip_code_prefix     REAL        0       None   0
33   33                    seller_city     TEXT        0       None   0
34   34                   seller_state     TEXT        0       None   0
35   35                  payment_value     REAL        0       None   0
36   36           payment_installments     REAL        0       None   0
37   37                   payment_type     TEXT        0       None   0
38   38                  payment_count     REAL        0       None   0
39   39                   review_score     REAL        0       None   0
40   40                   review_count     REAL        0       None   0
41   41           review_comment_title     TEXT        0       None   0
42   42         review_comment_message     TEXT        0       None   0

In [9]:
pd.read_sql("""
SELECT
    SUM(CASE WHEN order_id IS NULL THEN 1 ELSE 0 END) AS missing_order_id,
    SUM(CASE WHEN customer_id IS NULL THEN 1 ELSE 0 END) AS missing_customer_id
FROM orders;
""", conn)

   missing_order_id  missing_customer_id
0                 0                    0

In [10]:
pd.read_sql("""
SELECT *
FROM orders
LIMIT 10;
""", conn)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,purchase_year,purchase_month,...,seller_city,seller_state,payment_value,payment_installments,payment_type,payment_count,review_score,review_count,review_comment_title,review_comment_message
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,2017,10,...,maua,SP,38.71,1.0,"credit_card, voucher",3.0,4.0,1.0,None,"Não testei o produto ainda, mas ele veio corre..."
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,2018,7,...,belo horizonte,SP,141.46,1.0,boleto,1.0,4.0,1.0,Muito boa a loja,Muito bom o produto.
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,2018,8,...,guariba,SP,179.12,3.0,credit_card,1.0,5.0,1.0,None,None
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,2017,11,...,belo horizonte,MG,72.20,1.0,credit_card,1.0,5.0,1.0,None,O produto foi exatamente o que eu esperava e e...
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,2018,2,...,mogi das cruzes,SP,28.62,1.0,credit_card,1.0,5.0,1.0,None,None
5,a4591c265e18cb1dcee52889e2d8acc3,503740e9ca751ccdda7ba28e9ab8f608,delivered,2017-07-09 21:57:05,2017-07-09 22:10:13,2017-07-11 14:58:04,2017-07-26 10:57:55,2017-08-01,2017,7,...,guarulhos,SP,175.26,6.0,credit_card,1.0,4.0,1.0,None,None
6,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,None,None,2017-05-09,2017,4,...,sao paulo,SP,65.95,1.0,credit_card,1.0,2.0,1.0,None,fiquei triste por n ter me atendido.
7,6514b8ad8028c9f2cc2374ded245783f,9bdf08b4b3b52b5526ff42d37d47f222,delivered,2017-05-16 13:10:30,2017-05-16 13:22:11,2017-05-22 10:07:46,2017-05-26 12:55:51,2017-06-07,2017,5,...,atibaia,SP,75.16,3.0,credit_card,1.0,5.0,1.0,None,None
8,76c6e866289321a7c93b82b54852dc33,f54a9f0e6b351c431402b8461ea51999,delivered,2017-01-23 18:29:09,2017-01-25 02:50:47,2017-01-26 14:16:31,2017-02-02 14:08:10,2017-03-06,2017,1,...,sao jose do rio pardo,SP,35.95,1.0,boleto,1.0,1.0,1.0,None,None
9,e69bfb5eb88e0ed6a785585b27e16dbf,31ad1d1b63eb9962463f764d4e6e0c9d,delivered,2017-07-29 11:55:02,2017-07-29 12:05:32,2017-08-10 19:45:24,2017-08-16 17:14:30,2017-08-23,2017,7,...,itaquaquecetuba,SP,169.76,1.0,"credit_card, voucher",2.0,5.0,1.0,None,None

In [12]:
# KPI 1
pd.read_sql("""
SELECT
    ROUND(SUM(payment_value), 2) AS total_revenue
FROM orders;
""", conn)

   total_revenue
0    20470726.66

# Sales KPI 1: Total Revenue

### Business Question
What is the total revenue generated from all customer orders?

### Objective
Calculate the total amount of revenue collected from all completed transactions in the dataset.

### SQL Function Used
- `SUM()` – Calculates the total value of all payments.
- `ROUND()` – Rounds the result to two decimal places.

### Why It Matters
Total revenue is one of the most important business metrics, providing an overall measure of sales performance. It helps stakeholders evaluate business growth, compare performance over time, and make strategic decisions.

### Insight
The query returns the total revenue generated across all recorded customer orders. This metric serves as a baseline for evaluating overall business performance.

In [ ]:
#KPI 2
pd.read_sql("""
SELECT
    COUNT(DISTINCT order_id) AS total_orders
FROM orders;
""", conn)

   total_orders
0         99441

# Sales KPI 2: Total Orders

### Business Question
How many unique orders were placed by customers?

### Objective
Determine the total number of distinct customer orders in the dataset.

### SQL Function Used
- `COUNT(DISTINCT order_id)` – Counts each order only once.

### Why It Matters
Total orders indicate customer purchasing activity and overall business volume. Monitoring this metric helps evaluate demand trends and supports operational planning.

### Insight
The query returns the total number of unique orders processed by the business, providing a key indicator of transaction volume.

In [17]:
#KPI 3
pd.read_sql("""
SELECT
    ROUND(SUM(payment_value) / COUNT(DISTINCT order_id), 2) AS average_order_value
FROM orders;
""", conn)

   average_order_value
0               205.86

# Sales KPI 3: Average Order Value (AOV)

### Business Question
What is the average revenue generated per customer order?

### Objective
Calculate the average amount spent per order.

### SQL Function Used
- `SUM(payment_value)` – Calculates total revenue.
- `COUNT(DISTINCT order_id)` – Counts unique orders.
- `ROUND()` – Formats the result to two decimal places.

### Why It Matters
Average Order Value (AOV) measures how much customers spend on average during each purchase. Increasing AOV is often a key business objective because it improves revenue without necessarily increasing the number of customers.

### Insight
The query calculates the average revenue generated from each order, helping assess customer purchasing behavior and overall sales efficiency.

In [18]:
# KPI 4
pd.read_sql("""
SELECT
    COUNT(DISTINCT customer_unique_id) AS total_customers
FROM orders;
""", conn)

   total_customers
0            96096

# Customer KPI 4: Total Customers

### Business Question
How many unique customers have made purchases?

### Objective
Determine the total number of distinct customers represented in the dataset.

### SQL Function Used
- `COUNT(DISTINCT customer_unique_id)` – Counts each customer only once.

### Why It Matters
The total customer count provides insight into the size of the customer base. Tracking this metric helps businesses measure customer acquisition, market reach, and long-term growth.

### Insight
The query returns the total number of unique customers who placed orders, serving as a foundation for customer analytics and segmentation.

In [19]:
pd.read_sql("""
SELECT
    purchase_year,
    purchase_month,
    ROUND(SUM(payment_value), 2) AS monthly_revenue
FROM orders
GROUP BY purchase_year, purchase_month
ORDER BY purchase_year, purchase_month;
""", conn)

    purchase_year  purchase_month  monthly_revenue
0            2016               9           388.47
1            2016              10         76120.17
2            2016              12            19.62
3            2017               1        189015.66
4            2017               2        349701.93
5            2017               3        544738.23
6            2017               4        510891.55
7            2017               5        731017.09
8            2017               6        608891.38
9            2017               7        744599.53
10           2017               8        876129.37
11           2017               9       1023095.49
12           2017              10       1031505.53
13           2017              11       1599444.18
14           2017              12       1057582.34
15           2018               1       1415348.54
16           2018               2       1311260.71
17           2018               3       1480045.50
18           2018               4       1497843.94
19           2018               5       1511113.00
20           2018               6       1298685.81
21           2018               7       1359421.48
22           2018               8       1248837.93
23           2018               9          4439.54
24           2018              10           589.67

# Sales KPI 5: Monthly Revenue Trend

### Business Question
How does monthly revenue change over time?

### Objective
Analyze revenue generated each month to identify business growth patterns and seasonal trends.

### SQL Functions Used
- `SUM()`
- `GROUP BY`
- `ORDER BY`

### Why It Matters
Tracking monthly revenue helps identify seasonal demand, monitor business growth, and evaluate the impact of promotions or market changes.

### Insight
The query summarizes total revenue for each month, allowing stakeholders to observe revenue trends over time.

In [ ]:
#KPI 6
pd.read_sql("""
SELECT
    purchase_year,
    purchase_month,
    COUNT(DISTINCT order_id) AS total_orders
FROM orders
GROUP BY purchase_year, purchase_month
ORDER BY purchase_year, purchase_month;
""", conn)

    purchase_year  purchase_month  total_orders
0            2016               9             4
1            2016              10           324
2            2016              12             1
3            2017               1           800
4            2017               2          1780
5            2017               3          2682
6            2017               4          2404
7            2017               5          3700
8            2017               6          3245
9            2017               7          4026
10           2017               8          4331
11           2017               9          4285
12           2017              10          4631
13           2017              11          7544
14           2017              12          5673
15           2018               1          7269
16           2018               2          6728
17           2018               3          7211
18           2018               4          6939
19           2018               5          6873
20           2018               6          6167
21           2018               7          6292
22           2018               8          6512
23           2018               9            16
24           2018              10             4

# Sales KPI 6: Monthly Order Volume

### Business Question
How many customer orders are placed each month?

### Objective
Analyze the monthly order volume to understand purchasing trends and business activity over time.

### SQL Functions Used
- `COUNT(DISTINCT order_id)` – Counts unique customer orders.
- `GROUP BY` – Groups data by year and month.
- `ORDER BY` – Displays results in chronological order.

### Why It Matters
Monthly order volume helps businesses monitor customer demand, identify seasonal patterns, and evaluate the effectiveness of marketing campaigns or operational strategies.

### Insight
The query returns the total number of unique orders placed each month, providing a clear view of how customer purchasing activity changes over time.

In [21]:
#KPI 7
pd.read_sql("""
SELECT
    purchase_year,
    purchase_month,
    ROUND(
        SUM(payment_value) /
        COUNT(DISTINCT order_id),2
    ) AS average_order_value
FROM orders
GROUP BY purchase_year, purchase_month
ORDER BY purchase_year, purchase_month;
""", conn)

    purchase_year  purchase_month  average_order_value
0            2016               9                97.12
1            2016              10               234.94
2            2016              12                19.62
3            2017               1               236.27
4            2017               2               196.46
5            2017               3               203.11
6            2017               4               212.52
7            2017               5               197.57
8            2017               6               187.64
9            2017               7               184.95
10           2017               8               202.29
11           2017               9               238.76
12           2017              10               222.74
13           2017              11               212.02
14           2017              12               186.42
15           2018               1               194.71
16           2018               2               194.90
17           2018               3               205.25
18           2018               4               215.86
19           2018               5               219.86
20           2018               6               210.59
21           2018               7               216.06
22           2018               8               191.77
23           2018               9               277.47
24           2018              10               147.42

# Sales KPI 7: Average Monthly Order Value (AOV)

### Business Question
What is the average amount customers spend per order each month?

### Objective
Calculate the monthly Average Order Value (AOV) to understand customer spending behavior over time.

### SQL Functions Used
- `SUM(payment_value)` – Calculates total monthly revenue.
- `COUNT(DISTINCT order_id)` – Counts unique monthly orders.
- `ROUND()` – Formats the result to two decimal places.
- `GROUP BY` – Groups data by year and month.

### Why It Matters
Tracking monthly AOV helps businesses identify changes in customer purchasing behavior, evaluate pricing strategies, and measure the success of promotional campaigns.

### Insight
The query calculates the average revenue generated per order for each month, making it easier to compare customer spending trends across different periods.

In [22]:
#KPI 8 
pd.read_sql("""
SELECT
    purchase_weekday,
    COUNT(DISTINCT order_id) AS total_orders
FROM orders
GROUP BY purchase_weekday
ORDER BY total_orders DESC;
""", conn)

  purchase_weekday  total_orders
0           Monday         16196
1          Tuesday         15963
2        Wednesday         15552
3         Thursday         14761
4           Friday         14122
5           Sunday         11960
6         Saturday         10887

# Sales KPI 8: Orders by Day of the Week

### Business Question
On which day of the week do customers place the most orders?

### Objective
Identify the distribution of customer orders across the days of the week.

### SQL Functions Used
- `COUNT(DISTINCT order_id)` – Counts unique orders.
- `GROUP BY` – Groups data by weekday.
- `ORDER BY` – Sorts the results from highest to lowest order count.

### Why It Matters
Understanding which weekdays experience the highest order volume helps businesses optimize staffing, inventory management, and marketing campaigns to match customer demand.

### Insight
The query ranks weekdays by the number of customer orders, highlighting peak shopping days and periods of lower purchasing activity.

In [23]:
#KPI 9 
pd.read_sql("""
SELECT
    purchase_weekday,
    ROUND(SUM(payment_value),2) AS revenue
FROM orders
GROUP BY purchase_weekday
ORDER BY revenue DESC;
""", conn)

  purchase_weekday     revenue
0          Tuesday  3340461.15
1           Monday  3335776.83
2        Wednesday  3183123.63
3         Thursday  3127936.94
4           Friday  3035921.47
5           Sunday  2285063.41
6         Saturday  2162443.23

# Sales KPI 9: Revenue by Day of the Week

### Business Question
Which day of the week generates the highest revenue?

### Objective
Measure total revenue generated on each weekday to identify the most profitable shopping days.

### SQL Functions Used
- `SUM(payment_value)` – Calculates total revenue.
- `ROUND()` – Formats revenue to two decimal places.
- `GROUP BY` – Groups data by weekday.
- `ORDER BY` – Ranks weekdays by revenue.

### Why It Matters
Revenue by weekday helps businesses identify high-performing sales periods, schedule promotions strategically, and allocate operational resources more effectively.

### Insight
The query summarizes total revenue for each weekday, allowing comparison of daily sales performance and identification of the most profitable days.

In [24]:
# KPI 10 
pd.read_sql("""
SELECT
    ROUND(AVG(delivery_days),2) AS average_delivery_days
FROM orders;
""", conn)

   average_delivery_days
0                  12.01

# Delivery KPI 10: Average Delivery Time

### Business Question
How long does it take, on average, for an order to be delivered to the customer?

### Objective
Calculate the average number of days required to deliver customer orders.

### SQL Functions Used
- `AVG(delivery_days)` – Computes the average delivery duration.
- `ROUND()` – Formats the average to two decimal places.

### Why It Matters
Delivery time is a critical operational KPI that directly impacts customer satisfaction, retention, and overall service quality. Monitoring this metric helps identify opportunities to improve logistics and supply chain efficiency.

### Insight
The query returns the average delivery time across all delivered orders, providing an overall measure of the company's fulfillment performance.

In [25]:
#KPI 11
pd.read_sql("""
SELECT
    COUNT(*) AS repeat_customers
FROM (
    SELECT
        customer_unique_id,
        COUNT(DISTINCT order_id) AS total_orders
    FROM orders
    GROUP BY customer_unique_id
    HAVING COUNT(DISTINCT order_id) > 1
);
""", conn)

   repeat_customers
0              2997

# Customer KPI 11: Total Repeat Customers

### Business Question
How many customers have made more than one purchase?

### Objective
Identify the number of repeat customers by counting customers who placed multiple orders.

### SQL Functions Used
- `COUNT(DISTINCT order_id)`
- `GROUP BY`
- `HAVING`
- Subquery

### Why It Matters
Repeat customers indicate customer loyalty and satisfaction. A higher number of repeat customers often leads to increased profitability and lower customer acquisition costs.

### Insight
The query counts customers who placed more than one order, providing a measure of customer retention.

In [26]:
#KPI 12
pd.read_sql("""
SELECT
    customer_unique_id,
    ROUND(SUM(payment_value),2) AS total_spent
FROM orders
GROUP BY customer_unique_id
ORDER BY total_spent DESC
LIMIT 10;
""", conn)

                 customer_unique_id  total_spent
0  0a0a92112bd4c708ca5fde585afaa872    109312.64
1  698e1cf81d01a3d389d96145f7fa6df8     45256.00
2  c402f431464c72e27330a67f7b94d4fb     44048.00
3  4007669dec559734d6f53e029e360987     36489.24
4  ef8d54b3797ea4db1d63f0ced6a906e9     30186.00
5  763c8b1c9c68a0229c42c9fc6f662b93     29099.52
6  c8460e4251689ba205045f3ea17884a1     27935.46
7  eae0a83d752b1dd32697e0e7b4221656     25051.89
8  3d47f4368ccc8e1bb4c4a12dbda7111b     22346.60
9  adfa1cab2b2c8706db21bb13c0a1beb1     19457.04

# Customer KPI 12: Top 10 Customers by Revenue

### Business Question
Which customers contribute the highest revenue?

### Objective
Identify the highest-value customers based on their total spending.

### SQL Functions Used
- `SUM()`
- `GROUP BY`
- `ORDER BY`
- `LIMIT`

### Why It Matters
High-value customers are critical for business growth. Identifying them supports loyalty programs, personalized marketing, and customer retention strategies.

### Insight
The query ranks customers based on total spending and returns the top 10 highest-revenue customers.

In [27]:
# KPI 13
pd.read_sql("""
SELECT
    customer_unique_id,
    COUNT(DISTINCT order_id) AS total_orders,
    ROUND(SUM(payment_value),2) AS customer_lifetime_value
FROM orders
GROUP BY customer_unique_id
ORDER BY customer_lifetime_value DESC;
""", conn)

                     customer_unique_id  total_orders  customer_lifetime_value
0      0a0a92112bd4c708ca5fde585afaa872             1                109312.64
1      698e1cf81d01a3d389d96145f7fa6df8             1                 45256.00
2      c402f431464c72e27330a67f7b94d4fb             1                 44048.00
3      4007669dec559734d6f53e029e360987             1                 36489.24
4      ef8d54b3797ea4db1d63f0ced6a906e9             1                 30186.00
...                                 ...           ...                      ...
96091  bd06ce0e06ad77a7f681f1a4960a3cc6             1                    10.07
96092  317cfc692e3f86c45c95697c61c853a6             1                     9.59
96093  968fac81e2c44fb6c1e3ac2a45e6a102             1                     0.00
96094  4fa4365000c7090fcb8cad5713c6d3db             1                     0.00
96095  830d5b7aaa3b6f1e9ad63703bec97d23             1                      NaN

[96096 rows x 3 columns]

# Customer KPI 13: Customer Lifetime Value (CLV)

### Business Question
What is the lifetime value of each customer?

### Objective
Calculate the total revenue generated by each customer throughout their purchasing history.

### SQL Functions Used
- `SUM()`
- `COUNT(DISTINCT)`
- `GROUP BY`

### Why It Matters
Customer Lifetime Value helps businesses identify their most profitable customers and prioritize long-term relationship-building efforts.

### Insight
The query estimates each customer's lifetime value by summing all payments associated with their orders.

In [28]:
# KPI 14
pd.read_sql("""
SELECT
    ROUND(
        AVG(total_orders),
        2
    ) AS avg_orders_per_customer
FROM (
    SELECT
        customer_unique_id,
        COUNT(DISTINCT order_id) AS total_orders
    FROM orders
    GROUP BY customer_unique_id
);
""", conn)

   avg_orders_per_customer
0                     1.03

# Customer KPI 14: Average Orders per Customer

### Business Question
How many orders does the average customer place?

### Objective
Measure the average purchasing frequency across all customers.

### SQL Functions Used
- `COUNT(DISTINCT)`
- `AVG()`
- `GROUP BY`
- Subquery

### Why It Matters
Average orders per customer provide insight into customer engagement and repeat purchasing behavior.

### Insight
The query calculates the average number of orders placed by each customer, helping evaluate customer retention and purchasing frequency.

In [29]:
# kPI 15
pd.read_sql("""
SELECT
    total_orders,
    COUNT(*) AS number_of_customers
FROM (
    SELECT
        customer_unique_id,
        COUNT(DISTINCT order_id) AS total_orders
    FROM orders
    GROUP BY customer_unique_id
)
GROUP BY total_orders
ORDER BY total_orders;
""", conn)

   total_orders  number_of_customers
0             1                93099
1             2                 2745
2             3                  203
3             4                   30
4             5                    8
5             6                    6
6             7                    3
7             9                    1
8            17                    1

# Customer KPI 15: Customer Order Frequency Distribution

### Business Question
How are customers distributed based on the number of orders they have placed?

### Objective
Analyze customer purchasing frequency by grouping customers according to their total order count.

### SQL Functions Used
- `COUNT(DISTINCT)`
- `GROUP BY`
- `COUNT(*)`
- Subquery

### Why It Matters
Understanding purchase frequency helps identify one-time buyers, repeat customers, and highly engaged customers, enabling targeted retention and marketing strategies.

### Insight
The query groups customers by their total number of orders, providing a clear picture of customer purchasing behavior across the business.

In [30]:
#KPI 16
pd.read_sql("""
SELECT
    product_category_name_english,
    ROUND(SUM(payment_value), 2) AS total_revenue
FROM orders
GROUP BY product_category_name_english
ORDER BY total_revenue DESC
LIMIT 10;
""", conn)

  product_category_name_english  total_revenue
0                bed_bath_table     1712553.67
1                 health_beauty     1657373.12
2         computers_accessories     1585330.45
3               furniture_decor     1430176.39
4                 watches_gifts     1429216.68
5                sports_leisure     1392127.56
6                    housewares     1094758.13
7                          auto      852294.33
8                  garden_tools      838280.75
9                    cool_stuff      779698.00

# Product KPI 16: Top 10 Product Categories by Revenue

### Business Question
Which product categories contribute the most revenue?

### Objective
Identify the highest revenue-generating product categories.

### SQL Functions Used
- `SUM()`
- `GROUP BY`
- `ORDER BY`
- `LIMIT`

### Why It Matters
Understanding revenue by product category helps businesses prioritize inventory, marketing investments, and merchandising strategies.

### Insight
The query ranks product categories based on total revenue and returns the top ten highest-performing categories.

In [31]:
# KPI 17
pd.read_sql("""
SELECT
    product_category_name_english,
    COUNT(DISTINCT order_id) AS total_orders
FROM orders
GROUP BY product_category_name_english
ORDER BY total_orders DESC
LIMIT 10;
""", conn)

  product_category_name_english  total_orders
0                bed_bath_table          9417
1                 health_beauty          8836
2                sports_leisure          7720
3         computers_accessories          6689
4               furniture_decor          6449
5                    housewares          5884
6                 watches_gifts          5624
7                     telephony          4199
8                          auto          3897
9                          toys          3886

# Product KPI 17: Top 10 Categories by Order Volume

### Business Question
Which product categories are purchased most frequently?

### Objective
Determine which categories receive the highest number of customer orders.

### SQL Functions Used
- `COUNT(DISTINCT)`
- `GROUP BY`
- `ORDER BY`
- `LIMIT`

### Why It Matters
High order volume indicates customer demand. Comparing order volume with revenue can reveal whether categories succeed because of high sales volume or higher-priced products.

### Insight
The query identifies the ten product categories with the greatest number of customer orders.

In [32]:
# KPI 18
pd.read_sql("""
SELECT
    product_category_name_english,
    ROUND(AVG(price), 2) AS average_price
FROM orders
GROUP BY product_category_name_english
ORDER BY average_price DESC
LIMIT 10;
""", conn)

           product_category_name_english  average_price
0                              computers        1098.34
1  small_appliances_home_oven_and_coffee         624.29
2                      home_appliances_2         476.12
3             agro_industry_and_commerce         342.12
4                    musical_instruments         281.62
5                       small_appliances         280.78
6                        fixed_telephony         225.69
7              construction_tools_safety         208.99
8                          watches_gifts         201.14
9                       air_conditioning         185.27

# Product KPI 18: Average Product Price by Category

### Business Question
Which product categories have the highest average selling price?

### Objective
Calculate the average product price for each category.

### SQL Functions Used
- `AVG()`
- `ROUND()`
- `GROUP BY`
- `ORDER BY`

### Why It Matters
Average selling price helps businesses understand pricing strategies, identify premium product categories, and compare customer purchasing behavior across categories.

### Insight
The query ranks product categories based on their average product price.

In [33]:
# KPI 19
pd.read_sql("""
SELECT
    product_id,
    product_category_name_english,
    ROUND(SUM(payment_value), 2) AS total_revenue
FROM orders
GROUP BY product_id, product_category_name_english
ORDER BY total_revenue DESC
LIMIT 10;
""", conn)

,product_id,product_category_name_english,total_revenue
0,None,None,162591.95
1,5769ef0a239114ac3a854af00df129e4,fixed_telephony,109312.64
2,bb50f2e236e5eea0100680137654686c,health_beauty,81887.42
3,422879e10f46682990de24d770e7f83d,garden_tools,79512.22
4,d1c427060a0f73f6b889a5c7c61f2ac4,computers_accessories,70557.90
5,6cdd53843498f92890544667809f1595,health_beauty,64825.67
6,d5991653e037ccb7af6ed7d94246b249,computers_accessories,64143.26
7,aca2eb7d00ea1a7b8ebd4e68314663af,furniture_decor,63788.12
8,a62e25e09e05e6faf31d90c6ec1aa3d1,watches_gifts,63167.37
9,99a4788cb24856965c36a24e339b6058,bed_bath_table,63161.40

# Product KPI 19: Highest Revenue Products

### Business Question
Which individual products generate the highest revenue?

### Objective
Identify the top-performing products based on total revenue.

### SQL Functions Used
- `SUM()`
- `GROUP BY`
- `ORDER BY`
- `LIMIT`

### Why It Matters
Identifying high-performing products supports inventory planning, promotional campaigns, and product portfolio optimization.

### Insight
The query ranks individual products by total revenue and returns the ten highest-performing products.

In [34]:
# KPI 20 
pd.read_sql("""
SELECT
    product_category_name_english,
    COUNT(DISTINCT order_id) AS total_orders,
    ROUND(SUM(payment_value), 2) AS total_revenue,
    ROUND(AVG(price), 2) AS average_price
FROM orders
GROUP BY product_category_name_english
ORDER BY total_revenue DESC;
""", conn)

   product_category_name_english  total_orders  total_revenue  average_price
0                 bed_bath_table          9417     1712553.67          93.30
1                  health_beauty          8836     1657373.12         130.16
2          computers_accessories          6689     1585330.45         116.51
3                furniture_decor          6449     1430176.39          87.56
4                  watches_gifts          5624     1429216.68         201.14
..                           ...           ...            ...            ...
67                       flowers            29        2213.01          33.64
68                home_comfort_2            24        1710.54          25.34
69             cds_dvds_musicals            12        1199.43          52.14
70     fashion_childrens_clothes             8         785.67          71.23
71         security_and_services             2         324.51         141.64

[72 rows x 4 columns]

# Product KPI 20: Product Category Performance Summary

### Business Question
How does each product category perform across key business metrics?

### Objective
Summarize product category performance using total orders, total revenue, and average product price.

### SQL Functions Used
- `COUNT(DISTINCT)`
- `SUM()`
- `AVG()`
- `GROUP BY`

### Why It Matters
A consolidated performance summary enables stakeholders to compare categories across multiple dimensions and make informed decisions regarding pricing, inventory, and marketing investments.

### Insight
The query provides a comprehensive overview of each product category, combining demand, revenue generation, and pricing into a single analytical view.

In [35]:
# KPI 21
pd.read_sql("""
SELECT
    seller_id,
    ROUND(SUM(payment_value), 2) AS total_revenue
FROM orders
GROUP BY seller_id
ORDER BY total_revenue DESC
LIMIT 10;
""", conn)

                          seller_id  total_revenue
0  7c67e1448b00f6e969d365cea6b010ab      507166.91
1  1025f0e2d44d7041d6cf58b6550e0bfa      308222.04
2  4a3ca9315b744ce9f8e9374361493884      301245.27
3  1f50f920176fa81dab994f9023523100      290253.42
4  53243585a1d6dc2643021fd1853d8905      284903.08
5  da8622b14eb17ae2831f4ac5b9dab84a      272219.32
6  4869f7a5dfa277a7dca6462dcf3b52b2      264166.12
7  955fee9216a65b617aa5c0531780ce60      236322.30
8  fa1c13f2614d7b5c4749cbc52fecda94      206513.23
9  7e93a43ef30c4f03f38b393420bc753a      185134.21

# Seller KPI 21: Top 10 Sellers by Revenue

### Business Question
Which sellers generate the highest revenue?

### Objective
Identify the sellers contributing the most revenue to the marketplace.

### SQL Functions Used
- `SUM()`
- `GROUP BY`
- `ORDER BY`
- `LIMIT`

### Why It Matters
Top-performing sellers drive a significant portion of marketplace revenue. Identifying them helps support strategic partnerships, incentive programs, and seller retention initiatives.

### Insight
The query ranks sellers based on total revenue and returns the ten highest revenue-generating sellers.

In [36]:
# KPI 22
pd.read_sql("""
SELECT
    seller_id,
    COUNT(DISTINCT order_id) AS total_orders
FROM orders
GROUP BY seller_id
ORDER BY total_orders DESC
LIMIT 10;
""", conn)

                          seller_id  total_orders
0  6560211a19b47992c3666cc44a7e94c0          1854
1  4a3ca9315b744ce9f8e9374361493884          1806
2  cc419e0650a3c5ba77189a1882b7556a          1706
3  1f50f920176fa81dab994f9023523100          1404
4  da8622b14eb17ae2831f4ac5b9dab84a          1314
5  955fee9216a65b617aa5c0531780ce60          1287
6  7a67c85e85bb2ce8582c35f2203ad736          1160
7  ea8482cd71df3c1969d7b9473ff13abc          1146
8  4869f7a5dfa277a7dca6462dcf3b52b2          1132
9  3d871de0142ce09b7081e2b9d1733cb1          1080

# Seller KPI 22: Top 10 Sellers by Order Volume

### Business Question
Which sellers process the highest number of customer orders?

### Objective
Measure seller performance based on order volume.

### SQL Functions Used
- `COUNT(DISTINCT)`
- `GROUP BY`
- `ORDER BY`
- `LIMIT`

### Why It Matters
Order volume helps identify highly active sellers and provides insight into marketplace participation and operational workload.

### Insight
The query ranks sellers according to the total number of unique orders they have fulfilled.

In [37]:
# KPI 23
pd.read_sql("""
SELECT
    ROUND(AVG(total_revenue), 2) AS average_seller_revenue
FROM (
    SELECT
        seller_id,
        SUM(payment_value) AS total_revenue
    FROM orders
    GROUP BY seller_id
);
""", conn)

   average_seller_revenue
0                 6611.99

# Seller KPI 23: Average Revenue per Seller

### Business Question
How much revenue does the average seller generate?

### Objective
Calculate the average total revenue generated by sellers across the marketplace.

### SQL Functions Used
- `SUM()`
- `AVG()`
- `GROUP BY`
- Subquery

### Why It Matters
Average seller revenue provides a benchmark for evaluating seller performance and understanding revenue distribution across the marketplace.

### Insight
The query calculates the average revenue generated per seller by averaging each seller's total revenue.

In [38]:
# KPI 24
pd.read_sql("""
SELECT
    seller_id,
    ROUND(
        SUM(payment_value) /
        COUNT(DISTINCT order_id),
        2
    ) AS average_order_value
FROM orders
GROUP BY seller_id
ORDER BY average_order_value DESC
LIMIT 10;
""", conn)

                          seller_id  average_order_value
0  b37c4c02bda3161a7546a4e6d222d5b2             36329.76
1  0b36063d5818f81ccb94b54adfaebbf5             11745.00
2  c394e193cda3b4225ff2094d32184849             10259.61
3  8ff38bc3969e67c36c48343a07090f66              7719.12
4  80ceebb4ee9b31afb6c6a916a574a1e2              6922.21
5  ee27a8f15b1dded4d213a468ba4eb391              6726.66
6  a3b42d266fa8afc874b909422ce88582              5527.44
7  010da0602d7774602cd1b3f5fb7b709e              5398.75
8  f08a5b9dd6767129688d001acafc21e5              4400.13
9  fce62094ffe6a4009188ec44e681dfdd              3680.52

# Seller KPI 24: Highest Average Order Value

### Business Question
Which sellers generate the highest average revenue per order?

### Objective
Measure the average order value for each seller.

### SQL Functions Used
- `SUM()`
- `COUNT(DISTINCT)`
- `GROUP BY`
- `ORDER BY`

### Why It Matters
Average Order Value helps identify sellers specializing in premium products or high-value transactions.

### Insight
The query ranks sellers based on the average revenue generated for each customer order.

In [39]:
# KPI 25
pd.read_sql("""
SELECT
    seller_id,
    ROUND(AVG(delivery_days), 2) AS average_delivery_days
FROM orders
GROUP BY seller_id
HAVING COUNT(DISTINCT order_id) >= 10
ORDER BY average_delivery_days ASC
LIMIT 10;
""", conn)

                          seller_id  average_delivery_days
0                              None                    NaN
1  3fac58ce0ad699020c7944d53c41329c                   3.50
2  30a81d8cf85fb2ada1b1b094c9583a95                   3.65
3  5a413ade68e8f8d93071a7f52a64cb9e                   3.71
4  c3e1abd72a42fe690fcd89cf5720fe29                   3.92
5  508808d438fe2ff972ed13bb8f4a82e2                   4.00
6  41c2bad7229b0c25e6becf179ebf63ff                   4.30
7  bc2ac6b95e1accce9858528ee566c17e                   4.41
8  4736e9d642ef4257cd7622516931eb51                   4.50
9  aac51c486b672a9850d59f3e84b1cf88                   4.54

# Seller KPI 25: Fastest Sellers by Average Delivery Time

### Business Question
Which sellers deliver customer orders the fastest?

### Objective
Evaluate seller performance by measuring the average delivery time for sellers with a sufficient number of completed orders.

### SQL Functions Used
- `AVG()`
- `GROUP BY`
- `HAVING`
- `ORDER BY`

### Why It Matters
Delivery speed is a key operational metric that directly influences customer satisfaction and marketplace performance.

### Insight
The query identifies sellers with the shortest average delivery times while considering only sellers with at least ten completed orders to ensure meaningful comparisons.

In [40]:
#KPI 26
pd.read_sql("""
SELECT
    order_status,
    COUNT(DISTINCT order_id) AS total_orders,
    ROUND(
        COUNT(DISTINCT order_id) * 100.0 /
        (SELECT COUNT(DISTINCT order_id) FROM orders),
        2
    ) AS percentage
FROM orders
GROUP BY order_status
ORDER BY total_orders DESC;
""", conn)

  order_status  total_orders  percentage
0    delivered         96478       97.02
1      shipped          1107        1.11
2     canceled           625        0.63
3  unavailable           609        0.61
4     invoiced           314        0.32
5   processing           301        0.30
6      created             5        0.01
7     approved             2        0.00

# Delivery KPI 26: Order Status Distribution

### Business Question
What proportion of customer orders fall into each order status?

### Objective
Analyze the distribution of orders across different fulfillment statuses.

### SQL Functions Used
- `COUNT(DISTINCT)`
- `GROUP BY`
- Subquery
- `ROUND()`

### Why It Matters
Order status distribution provides insight into operational efficiency and customer fulfillment performance. A high percentage of delivered orders generally indicates a healthy fulfillment process.

### Insight
The query summarizes the number and percentage of orders for each order status, allowing stakeholders to evaluate the overall order fulfillment process.

In [41]:
#KPI 27
pd.read_sql("""
SELECT
    customer_state,
    ROUND(AVG(delivery_days), 2) AS average_delivery_days,
    COUNT(DISTINCT order_id) AS total_orders
FROM orders
GROUP BY customer_state
HAVING COUNT(DISTINCT order_id) >= 100
ORDER BY average_delivery_days DESC;
""", conn)

   customer_state  average_delivery_days  total_orders
0              AM                  25.96           148
1              AL                  23.99           413
2              PA                  23.30           975
3              MA                  21.20           747
4              SE                  20.98           350
5              CE                  20.54          1336
6              PB                  20.12           536
7              RO                  19.28           253
8              PI                  18.93           495
9              RN                  18.87           485
10             BA                  18.77          3380
11             PE                  17.79          1652
12             MT                  17.51           907
13             TO                  17.00           280
14             ES                  15.19          2033
15             MS                  15.11           715
16             GO                  14.95          2020
17             RS                  14.71          5466
18             RJ                  14.69         12852
19             SC                  14.52          3637
20             DF                  12.50          2140
21             MG                  11.52         11635
22             PR                  11.48          5045
23             SP                   8.26         41746

# Delivery KPI 27: Average Delivery Time by Customer State

### Business Question
How does average delivery time vary across customer states?

### Objective
Compare delivery performance across geographic regions.

### SQL Functions Used
- `AVG()`
- `COUNT(DISTINCT)`
- `GROUP BY`
- `HAVING`
- `ORDER BY`

### Why It Matters
Regional delivery analysis helps identify logistics bottlenecks, optimize shipping networks, and improve customer satisfaction.

### Insight
The query compares average delivery times across states while excluding states with very few orders to ensure meaningful results.

In [42]:
# KPI 28
pd.read_sql("""
SELECT
    customer_state,
    ROUND(AVG(delivery_days), 2) AS average_delivery_days
FROM orders
GROUP BY customer_state
HAVING COUNT(DISTINCT order_id) >= 100
ORDER BY average_delivery_days DESC
LIMIT 10;
""", conn)

  customer_state  average_delivery_days
0             AM                  25.96
1             AL                  23.99
2             PA                  23.30
3             MA                  21.20
4             SE                  20.98
5             CE                  20.54
6             PB                  20.12
7             RO                  19.28
8             PI                  18.93
9             RN                  18.87

# Delivery KPI 28: Top 10 Slowest Delivery States

### Business Question
Which customer states have the slowest average delivery times?

### Objective
Identify geographic regions where delivery performance is weakest.

### SQL Functions Used
- `AVG()`
- `GROUP BY`
- `HAVING`
- `ORDER BY`
- `LIMIT`

### Why It Matters
Identifying regions with consistently slower deliveries enables businesses to improve logistics operations, optimize warehouse placement, and enhance customer satisfaction.

### Insight
The query ranks the ten states with the highest average delivery times, highlighting areas where operational improvements may be needed.

In [43]:
# KPI 29
pd.read_sql("""
SELECT
    COUNT(DISTINCT CASE
        WHEN DATE(order_delivered_customer_date) >
             DATE(order_estimated_delivery_date)
        THEN order_id
    END) AS late_orders,

    COUNT(DISTINCT order_id) AS total_orders,

    ROUND(
        COUNT(DISTINCT CASE
            WHEN DATE(order_delivered_customer_date) >
                 DATE(order_estimated_delivery_date)
            THEN order_id
        END) * 100.0 /
        COUNT(DISTINCT order_id),
        2
    ) AS late_delivery_percentage
FROM orders
WHERE order_delivered_customer_date IS NOT NULL;
""", conn)

   late_orders  total_orders  late_delivery_percentage
0         6535         96476                      6.77

# Delivery KPI 29: Late Delivery Rate

### Business Question
What percentage of customer orders were delivered after the estimated delivery date?

### Objective
Measure the frequency of late deliveries.

### SQL Functions Used
- `CASE WHEN`
- `COUNT(DISTINCT)`
- `DATE()`
- `ROUND()`

### Why It Matters
Late deliveries negatively impact customer satisfaction, increase support requests, and may reduce customer retention.

### Insight
The query calculates the total number and percentage of orders delivered after the promised delivery date, providing a key indicator of logistics performance.

In [44]:
# KPI 30
pd.read_sql("""
SELECT
    ROUND(
        AVG(
            JULIANDAY(order_delivered_customer_date) -
            JULIANDAY(order_estimated_delivery_date)
        ),
        2
    ) AS average_delivery_delay_days
FROM orders
WHERE order_delivered_customer_date IS NOT NULL
  AND order_estimated_delivery_date IS NOT NULL;
""", conn)

   average_delivery_delay_days
0                       -11.33

# Delivery KPI 30: Average Delivery Delay

### Business Question
On average, were orders delivered before or after the estimated delivery date?

### Objective
Measure the average difference between actual and estimated delivery dates.

### SQL Functions Used
- `JULIANDAY()`
- `AVG()`
- `ROUND()`

### Why It Matters
Comparing actual delivery dates with estimated delivery dates helps evaluate forecasting accuracy and overall logistics performance.

### Insight
The query calculates the average delivery delay in days. A negative value indicates that orders typically arrive earlier than promised, while a positive value indicates that deliveries are generally late.

In [45]:
# KPI 31
pd.read_sql("""
SELECT
    payment_type,
    COUNT(DISTINCT order_id) AS total_orders,
    ROUND(
        COUNT(DISTINCT order_id) * 100.0 /
        (SELECT COUNT(DISTINCT order_id) FROM orders),
        2
    ) AS percentage
FROM orders
GROUP BY payment_type
ORDER BY total_orders DESC;
""", conn)

              payment_type  total_orders  percentage
0              credit_card         74259       74.68
1                   boleto         19784       19.90
2     credit_card, voucher          2245        2.26
3                  voucher          1621        1.63
4               debit_card          1527        1.54
5              not_defined             3        0.00
6  credit_card, debit_card             1        0.00
7                     None             1        0.00

# Payment KPI 31: Payment Method Distribution

### Business Question
Which payment methods are most frequently used by customers?

### Objective
Analyze customer payment preferences by measuring the distribution of payment methods.

### SQL Functions Used
- `COUNT(DISTINCT)`
- `GROUP BY`
- `ROUND()`
- Subquery

### Why It Matters
Understanding payment preferences helps businesses optimize payment processing, improve customer experience, and negotiate with payment service providers.

### Insight
The query summarizes the number and percentage of orders for each payment method, highlighting the most commonly used payment options.

In [46]:
#KPI 32
pd.read_sql("""
SELECT
    payment_type,
    ROUND(SUM(payment_value), 2) AS total_revenue
FROM orders
GROUP BY payment_type
ORDER BY total_revenue DESC;
""", conn)

              payment_type  total_revenue
0              credit_card    15520455.62
1                   boleto     4086820.71
2     credit_card, voucher      400382.82
3               debit_card      256367.92
4                  voucher      206546.77
5  credit_card, debit_card         152.82
6              not_defined           0.00
7                     None            NaN

# Payment KPI 32: Revenue by Payment Method

### Business Question
Which payment methods generate the highest total revenue?

### Objective
Compare total revenue generated across different payment methods.

### SQL Functions Used
- `SUM()`
- `ROUND()`
- `GROUP BY`
- `ORDER BY`

### Why It Matters
Revenue by payment type helps businesses understand customer payment behavior and identify the payment methods contributing most to overall sales.

### Insight
The query ranks payment methods based on total revenue generated from customer transactions.

In [47]:
# KPI 33
pd.read_sql("""
SELECT
    payment_type,
    ROUND(AVG(payment_value), 2) AS average_payment_value
FROM orders
GROUP BY payment_type
ORDER BY average_payment_value DESC;
""", conn)

              payment_type  average_payment_value
0              credit_card                 183.80
1                   boleto                 177.40
2     credit_card, voucher                 159.77
3  credit_card, debit_card                 152.82
4               debit_card                 151.16
5                  voucher                 118.91
6              not_defined                   0.00
7                     None                    NaN

# Payment KPI 33: Average Payment Value by Payment Method

### Business Question
What is the average payment amount associated with each payment method?

### Objective
Calculate the average payment value for every payment type.

### SQL Functions Used
- `AVG()`
- `ROUND()`
- `GROUP BY`
- `ORDER BY`

### Why It Matters
Average payment value helps identify whether certain payment methods are commonly used for higher-value purchases.

### Insight
The query compares the average payment amount across different payment methods, revealing customer payment patterns.

In [48]:
#KPI 34
pd.read_sql("""
SELECT
    payment_installments,
    COUNT(*) AS total_payments,
    ROUND(AVG(payment_value), 2) AS average_payment_value
FROM orders
GROUP BY payment_installments
ORDER BY payment_installments;
""", conn)

    payment_installments  total_payments  average_payment_value
0                    NaN               3                    NaN
1                    0.0               3                 106.19
2                    1.0           54313                 142.87
3                    2.0           13737                 136.57
4                    3.0           11780                 155.59
5                    4.0            7992                 180.38
6                    5.0            6037                 198.84
7                    6.0            4623                 236.97
8                    7.0            1835                 195.62
9                    8.0            5050                 312.70
10                   9.0             735                 209.33
11                  10.0            6885                 436.66
12                  11.0              26                 123.98
13                  12.0             165                 326.23
14                  13.0              18                 148.68
15                  14.0              16                 174.35
16                  15.0              92                 425.06
17                  16.0               7                 395.08
18                  17.0               8                 174.60
19                  18.0              38                 498.61
20                  20.0              21                 568.07
21                  21.0               5                 267.43
22                  22.0               1                 228.71
23                  23.0               1                 236.48
24                  24.0              34                 810.74

# Payment KPI 34: Installment Payment Distribution

### Business Question
How do customers use installment payment options?

### Objective
Analyze the frequency of installment plans and the associated average payment values.

### SQL Functions Used
- `COUNT()`
- `AVG()`
- `ROUND()`
- `GROUP BY`

### Why It Matters
Installment analysis helps businesses understand financing preferences, customer affordability, and opportunities to optimize payment offerings.

### Insight
The query summarizes the number of payments and the average payment value for each installment option selected by customers.

In [49]:
# kpi 35
pd.read_sql("""
SELECT
    payment_type,
    ROUND(
        SUM(payment_value) /
        COUNT(DISTINCT order_id),
        2
    ) AS average_order_value
FROM orders
GROUP BY payment_type
ORDER BY average_order_value DESC;
""", conn)

              payment_type  average_order_value
0              credit_card               209.00
1                   boleto               206.57
2     credit_card, voucher               178.34
3               debit_card               167.89
4  credit_card, debit_card               152.82
5                  voucher               127.42
6              not_defined                 0.00
7                     None                  NaN

# Payment KPI 35: Average Order Value by Payment Method

### Business Question
Which payment methods are associated with the highest average order value?

### Objective
Measure the average revenue generated per order for each payment method.

### SQL Functions Used
- `SUM()`
- `COUNT(DISTINCT)`
- `ROUND()`
- `GROUP BY`
- `ORDER BY`

### Why It Matters
Average Order Value by payment method helps identify whether customers using specific payment options tend to make higher-value purchases, supporting targeted marketing and payment optimization strategies.

### Insight
The query calculates the average order value for each payment method, enabling comparisons of customer spending across payment preferences.